const errorCodes = {
  STATUS_FROM_NOT_EXIST: 'STATUS_FROM_NOT_EXIST',
  SERVER_NAME_NOT_FOUND: 'SERVER_NAME_NOT_FOUND',
  SERVER_NAME_TOO_SHORT: 'SERVER_NAME_TOO_SHORT',
  SERVER_NAME_TOO_LONG: 'SERVER_NAME_TOO_LONG',
  SERVER_STATUS_MUST_BE_BOOLEAN: 'SERVER_STATUS_MUST_BE_BOOLEAN',
};

export default errorCodes;
